### ISSUE TITLE
Pタグの漏れ

### ISSUE THREAD

**Issue by tsukasa-labz** [aws-samples/jp-contents-hub#4]
「VMware Cloud on AWS Immersion Day」のみPタグで囲われていません。

**Comment by Sugi275** [comment]
コメントありがとうございます。こちらは、MkDocs という Static Site Generator を使っている関係上、P タグで囲まれません。
箇条書きの中で、1個しか要素が無い場合は P タグが存在しない形になります。
(VMware 以外にも、SaaS も P タグに囲まれてないです :) )

こちら、P タグが無いことによる、不都合などありそうでしょうか？

**Comment by tsukasa-labz** [comment]
なるほど、そういう理由だったんですね。
スクレイピングしてリストをテーブル形式にしたところ、VMware部分が取得できていなかったので。。

**Comment by Sugi275** [comment]
他のアイデアとしては、ハンズオンコンテンツを羅列しているマークダウンから抜き出した方がもしかしたら簡単かもしれません。

https://raw.githubusercontent.com/aws-samples/jp-contents-hub/main/content/index.md

こちらの Issue は Close に出来ればと思います。

**Comment by tsukasa-labz** [comment]
スクレイピングの処理を修正して全て抽出できるように対応しました。
