### ISSUE TITLE
不要なカンマ

### ISSUE THREAD

**Issue by tsukasa-labz** [aws-samples/jp-contents-hub#5]
「Amazon FSx File Gateway ワークショップ」のタグ末尾に不要なカンマが混入しています。

**Comment by Sugi275** [comment]
ありがとうございます。こちら修正いたします。

**Comment by Sugi275** [comment]
こちら、修正完了したので、Close します！お知らせいただきありがとうございました。

**Comment by Sugi275** [comment]
関連 Commit
https://github.com/aws-samples/jp-contents-hub/commit/37fc5b8ef5018a8eb1a9326231205384a80a2796
