### ISSUE TITLE
「Introduction to Amazon ECS」のリンク切れ

### ISSUE THREAD

**Issue by miyohide** [aws-samples/jp-contents-hub#9]
「Introduction to Amazon ECS」へのリンクがPage not foundとなっていました。
https://github.com/aws-samples/jp-contents-hub/blob/5d61036101f47684cd01b19b8b706eaaf0644ad8/content/index.md?plain=1#L248

**Comment by Sugi275** [comment]
ご報告ありがとうございます！確認して利用ができないものでしたら削除いたします 🙇

**Comment by Sugi275** [comment]
利用できない状況でしたので、削除させていただきました。ご報告ありがとうございます、Close いたします
